# Generated by Django 5.2.4 on 2026-09-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigopareamento',
            name='turmas',
            field=models.ManyToManyField(related_name='codigos_pareamento_relacionados', through='api.CodigoPareamentoTurma', to='api.turma'),
        ),
        migrations.AddField(
            model_name='dispositivogravador',
            name='turmas',
            field=models.ManyToManyField(related_name='dispositivos_gravadores', through='api.DispositivoGravadorTurma', to='api.turma'),
        ),
        migrations.AlterField(
            model_name='audiodispositivo',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('processando', 'Processando'), ('processado', 'Processado'), ('falhou', 'Falhou'), ('comando', 'Comando de sala (sem relato)')], default='recebido', max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='faixa_etaria',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
