# Generated by Django 5.2.4 on 2025-12-04 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemCoordenacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('remetente', models.CharField(max_length=200, verbose_name='Nome do Remetente')),
                ('instituicao_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID da Instituição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem da Coordenação',
                'verbose_name_plural': 'Mensagens da Coordenação',
                'db_table': 'mensagens_coordenacao',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MensagemLida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True, verbose_name='ID do Usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='api.mensagemcoordenacao', verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem Lida',
                'verbose_name_plural': 'Mensagens Lidas',
                'db_table': 'mensagens_lidas',
                'managed': True,
                'unique_together': {('mensagem', 'usuario_id')},
            },
        ),
    ]
