# Generated by Django 5.2.4 on 2025-12-04 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mensagens_coordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaLido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(db_index=True, verbose_name='ID do Usuário')),
                ('alerta_tipo', models.CharField(max_length=50, verbose_name='Tipo do Alerta')),
                ('alerta_chave', models.CharField(max_length=200, verbose_name='Chave do Alerta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta Lido',
                'verbose_name_plural': 'Alertas Lidos',
                'db_table': 'alertas_lidos',
                'managed': True,
                'unique_together': {('usuario_id', 'alerta_tipo', 'alerta_chave')},
            },
        ),
    ]
