# Generated by Django 5.2.4 on 2025-12-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perguntabncc_pergunta_norma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perguntabncc',
            name='pergunta',
            field=models.TextField(verbose_name='Pergunta Facilitadora'),
        ),
    ]
