# Generated by Django 5.2.4 on 2026-01-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_periodo_avaliativo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='periodoavaliativo',
            new_name='periodos_av_institu_b05ab1_idx',
            old_name='periodos_avaliativos_instituicao_data_idx',
        ),
        migrations.AlterField(
            model_name='observacaotranscricao',
            name='crianca_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID da Criança'),
        ),
        migrations.AlterField(
            model_name='producaofotocrianca',
            name='crianca_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ID da Criança'),
        ),
    ]
