# Generated by Django 5.2.4 on 2026-01-26 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_periodos_avaliativos_instituicao_data_idx_periodos_av_institu_b05ab1_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaEspecialista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instituicao_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID da Instituição')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('nivel', models.CharField(max_length=50, verbose_name='Nível de Ensino')),
                ('pergunta', models.TextField(blank=True, null=True, verbose_name='Pergunta')),
                ('pergunta_facilitadora', models.TextField(verbose_name='Pergunta Facilitadora')),
                ('referencia_norma', models.CharField(max_length=50, verbose_name='Referência da Norma (Código BNCC)')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pergunta de Especialista',
                'verbose_name_plural': 'Perguntas de Especialistas',
                'db_table': 'perguntas_especialistas',
                'managed': True,
            },
        ),
    ]
