# Generated by Django 5.2.4 on 2026-01-26 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_perguntaespecialista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turma_id', models.UUIDField(db_index=True, unique=True, verbose_name='ID da Turma')),
                ('frequencia_registro', models.CharField(choices=[('diario', 'Diário'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal')], max_length=20, verbose_name='Frequência de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Registro',
                'verbose_name_plural': 'Configurações de Registro',
                'db_table': 'configuracoes_registro',
                'managed': True,
            },
        ),
    ]
