# Generated by Django 5.2.4 on 2026-02-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_campoexperienciacustomizado'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campoexperienciacustomizado',
            new_name='campos_expe_institu_629a7d_idx',
            old_name='campos_expe_institu_idx',
        ),
    ]
