# Generated by Django 5.2.4 on 2026-04-26 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_coordenacaocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nara_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pendente', 'Aguardando confirmação da professora'), ('confirmado', 'Confirmado pela professora'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('arquivo_path', models.CharField(blank=True, default='', max_length=500)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_hash', models.CharField(max_length=64, unique=True)),
                ('tamanho_arquivo', models.BigIntegerField(default=0)),
                ('tipo_arquivo', models.CharField(default='audio/ogg', max_length=50)),
                ('duracao_seg', models.FloatField(blank=True, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('feat_dim', models.IntegerField(blank=True, null=True)),
                ('classe_predita', models.CharField(blank=True, default='', max_length=50)),
                ('classe_escolhida', models.CharField(blank=True, default='', max_length=50)),
                ('probabilidades', models.JSONField(blank=True, default=dict)),
                ('anotacoes_professora', models.TextField(blank=True, default='')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Leitura',
                'verbose_name_plural': 'Registros de Leitura',
                'db_table': 'registro_leitura',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.RenameIndex(
            model_name='coordenacaocache',
            new_name='coordenacao_institu_0e5032_idx',
            old_name='coordenacao_cac_instit_b3a1d2_idx',
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='crianca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_leitura', to='api.crianca'),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_leitura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroleitura',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_leitura', to='api.turma'),
        ),
        migrations.AddIndex(
            model_name='registroleitura',
            index=models.Index(fields=['crianca', '-data_criacao'], name='registro_le_crianca_317fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='registroleitura',
            index=models.Index(fields=['status'], name='registro_le_status_5c8770_idx'),
        ),
    ]
