# Generated by Django 5.2.4 on 2026-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_registroleitura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroleitura',
            name='status',
            field=models.CharField(choices=[('pendente', 'Análise em andamento no NaraNN'), ('analisado', 'Análise pronta — aguardando confirmação da professora'), ('confirmado', 'Confirmado pela professora'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
