# Generated by Django 5.2.4 on 2026-05-09 15:00

from django.db import migrations, models
from django.db.models import Q


def preservar_legado_planejamento(apps, schema_editor):
    """Copia os 4 campos legados de planejamento para ``atividades_propostas``
    antes do drop, para que conteúdo digitado por professoras antes do
    Assistente de IA não suma silenciosamente.

    Layout final em ``atividades_propostas`` (cada bloco só aparece se
    tiver conteúdo):

        [texto já existente em atividades_propostas]

        — Materiais necessários —
        ...

        — Atividade para casa —
        ...

        — Observações —
        ...

    ``PlanejamentoSemanal.observacoes_gerais`` é prefixado em
    ``atividades_propostas`` do primeiro dia daquela semana, com cabeçalho
    ``— Observações da semana —``.

    Idempotente apenas no sentido de que, em ambientes onde esta migration
    já foi aplicada, o Django não a re-executa. Não tente rodar de novo
    manualmente — não há como detectar conteúdo "já preservado".
    """
    PlanejamentoDiario = apps.get_model('api', 'PlanejamentoDiario')
    PlanejamentoSemanal = apps.get_model('api', 'PlanejamentoSemanal')

    diarios = PlanejamentoDiario.objects.filter(
        Q(materiais_necessarios__isnull=False) & ~Q(materiais_necessarios='')
        | Q(atividade_casa__isnull=False) & ~Q(atividade_casa='')
        | Q(observacoes__isnull=False) & ~Q(observacoes='')
    )
    for pd in diarios.iterator():
        partes = []
        if (pd.atividades_propostas or '').strip():
            partes.append(pd.atividades_propostas.strip())
        if (pd.materiais_necessarios or '').strip():
            partes.append(f'— Materiais necessários —\n{pd.materiais_necessarios.strip()}')
        if (pd.atividade_casa or '').strip():
            partes.append(f'— Atividade para casa —\n{pd.atividade_casa.strip()}')
        if (pd.observacoes or '').strip():
            partes.append(f'— Observações —\n{pd.observacoes.strip()}')
        pd.atividades_propostas = '\n\n'.join(partes) or None
        pd.save(update_fields=['atividades_propostas'])

    semanais = PlanejamentoSemanal.objects.filter(
        observacoes_gerais__isnull=False,
    ).exclude(observacoes_gerais='')
    for ps in semanais.iterator():
        primeiro_dia = PlanejamentoDiario.objects.filter(
            planejamento_semanal=ps,
        ).order_by('data').first()
        if not primeiro_dia:
            continue
        cabecalho = f'— Observações da semana —\n{ps.observacoes_gerais.strip()}'
        corpo = (primeiro_dia.atividades_propostas or '').strip()
        primeiro_dia.atividades_propostas = (
            f'{cabecalho}\n\n{corpo}' if corpo else cabecalho
        )
        primeiro_dia.save(update_fields=['atividades_propostas'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_registroleitura_status'),
    ]

    operations = [
        # Preserva conteúdo dos 4 campos legados em `atividades_propostas`
        # ANTES dos RemoveField — sem isso, o drop apaga texto digitado
        # antes do Assistente de IA.
        migrations.RunPython(
            preservar_legado_planejamento,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='planejamentodiario',
            name='atividade_casa',
        ),
        migrations.RemoveField(
            model_name='planejamentodiario',
            name='materiais_necessarios',
        ),
        migrations.RemoveField(
            model_name='planejamentodiario',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='planejamentosemanal',
            name='observacoes_gerais',
        ),
        migrations.AddField(
            model_name='planejamentodiario',
            name='arquivo_content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planejamentodiario',
            name='arquivo_nome_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='planejamentodiario',
            name='arquivo_storage_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='planejamentodiario',
            name='prompt_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
