# Generated by Django 5.2.4 on 2026-05-14 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_planejamentodiario_atividade_casa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('input_tokens', models.BigIntegerField(verbose_name='Tokens de entrada')),
                ('image_tokens', models.BigIntegerField(default=0, verbose_name='Tokens de imagem')),
                ('output_tokens', models.BigIntegerField(verbose_name='Tokens de saída')),
                ('input_cost', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='Custo de entrada (USD)')),
                ('output_cost', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='Custo de saída (USD)')),
                ('total_cost', models.DecimalField(decimal_places=8, max_digits=14, verbose_name='Custo total (USD)')),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_openai', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável pela chamada')),
            ],
            options={
                'verbose_name': 'Uso da API OpenAI',
                'verbose_name_plural': 'Usos da API OpenAI',
                'db_table': 'openai_usage',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['-created_at'], name='openai_usag_created_9f472e_idx'), models.Index(fields=['model', '-created_at'], name='openai_usag_model_438bee_idx'), models.Index(fields=['usuario', '-created_at'], name='openai_usag_usuario_985519_idx')],
            },
        ),
    ]
