# Generated by Django 5.2.4 on 2026-05-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_openaiusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Prompt',
                'verbose_name_plural': 'Categorias de Prompt',
                'db_table': 'prompt_categorias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_global', models.TextField(blank=True, db_column='global', default='')),
                ('personalizado', models.TextField(blank=True, default='')),
                ('cliente_id', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.promptcategoria')),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompt',
                'db_table': 'prompt_templates',
                'managed': True,
            },
        ),
    ]
