# Generated by Django 5.2.15 on 2026-07-20 20:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_promptcategoria_prompttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaPAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('comunicacao', 'Comunicação e Linguagem'), ('motora', 'Desenvolvimento Motor'), ('socioemocional', 'Socioemocional'), ('cognitiva', 'Cognitiva'), ('avd', 'Atividades de Vida Diária'), ('academica', 'Acadêmica')], max_length=30)),
                ('inicio', models.DateField(verbose_name='Início da meta')),
                ('fim', models.DateField(verbose_name='Fim previsto da meta')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('criterio', models.TextField(verbose_name='Critério de sucesso')),
                ('estrategia', models.TextField(verbose_name='Estratégia')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('alcancada', 'Alcançada'), ('encerrada', 'Encerrada'), ('revisada', 'Revisada')], default='ativa', max_length=20, verbose_name='Status da meta')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_paee', to='api.crianca', verbose_name='Aluno')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_aee_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_paee', to='api.instituicao')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_paee', to='api.turma')),
            ],
            options={
                'verbose_name': 'Meta PAEE',
                'verbose_name_plural': 'Metas PAEE',
                'db_table': 'metas_paee',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessaoEspecialista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_atendimento', models.DateField(verbose_name='Data do atendimento')),
                ('duracao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (minutos)')),
                ('resumo', models.TextField(blank=True, default='', verbose_name='Resumo da sessão (IA, editável pelo especialista)')),
                ('status', models.CharField(choices=[('pendente', 'Processamento em andamento'), ('processado', 'Resumo gerado'), ('falhou', 'Falha no processamento')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('crianca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_especialista', to='api.crianca', verbose_name='Aluno')),
                ('especialista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_especialista', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_especialista', to='api.instituicao')),
                ('metas_trabalhadas', models.ManyToManyField(blank=True, db_table='sessoes_paee_metas', related_name='sessoes', to='api.metapaee', verbose_name='Metas trabalhadas na sessão')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_especialista', to='api.turma')),
            ],
            options={
                'verbose_name': 'Sessão Especialista',
                'verbose_name_plural': 'Sessões Especialista',
                'db_table': 'sessoes_especialista',
                'ordering': ['-data_atendimento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TarefaPAEE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField(verbose_name='Descrição da tarefa')),
                ('concluida', models.BooleanField(default=False)),
                ('observacao_professor', models.TextField(blank=True, default='', verbose_name='Observação do professor ao concluir')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='api.metapaee')),
                ('professor_conclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_aee_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Professor que concluiu')),
            ],
            options={
                'verbose_name': 'Tarefa PAEE',
                'verbose_name_plural': 'Tarefas PAEE',
                'db_table': 'tarefas_paee',
                'ordering': ['concluida', '-data_criacao'],
            },
        ),
    ]