# Generated by Django 5.2.15 on 2026-08-03 01:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_modelos_paee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoGravador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Identificador do hardware (MAC/serial)')),
                ('nome', models.CharField(blank=True, default='', max_length=120, verbose_name='Nome amigável (ex.: Gravador Sala 5C)')),
                ('token_hash', models.CharField(max_length=128, verbose_name='Hash do token de acesso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo (não revogado)')),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Último contato do dispositivo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_gravador', to='api.instituicao')),
                ('professora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_gravador', to=settings.AUTH_USER_MODEL, verbose_name='Professora vinculada')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_gravador', to='api.turma', verbose_name='Turma vinculada')),
            ],
            options={
                'verbose_name': 'Dispositivo gravador',
                'verbose_name_plural': 'Dispositivos gravadores',
                'db_table': 'dispositivos_gravador',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='CodigoPareamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_index=True, max_length=12, verbose_name='Código')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pareamento', to='api.instituicao')),
                ('professora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_pareamento', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_pareamento', to='api.turma')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_usados', to='api.dispositivogravador', verbose_name='Dispositivo que consumiu')),
            ],
            options={
                'verbose_name': 'Código de pareamento',
                'verbose_name_plural': 'Códigos de pareamento',
                'db_table': 'codigos_pareamento',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AudioDispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.UUIDField(verbose_name='UUID gerado pelo firmware (idempotência)')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256 do arquivo')),
                ('tamanho_arquivo', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('duracao_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('arquivo_path', models.CharField(max_length=500, verbose_name='Chave no storage')),
                ('status', models.CharField(choices=[('recebido', 'Recebido (aguardando processamento)'), ('processado', 'Processado (observações geradas)'), ('falhou', 'Falha no processamento')], default='recebido', max_length=20)),
                ('erro_processamento', models.TextField(blank=True, default='')),
                ('data_recebimento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios_dispositivo', to='api.instituicao')),
                ('observacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_dispositivo', to='api.observacaotranscricao', verbose_name='Observação gerada (relato individual)')),
                ('professora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_dispositivo', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_dispositivo', to='api.turma')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audios', to='api.dispositivogravador')),
            ],
            options={
                'verbose_name': 'Áudio de dispositivo',
                'verbose_name_plural': 'Áudios de dispositivos',
                'db_table': 'audios_dispositivo',
                'ordering': ['-data_recebimento'],
            },
        ),
        migrations.AddIndex(
            model_name='dispositivogravador',
            index=models.Index(fields=['instituicao', 'ativo'], name='dispositivo_institu_388bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='audiodispositivo',
            index=models.Index(fields=['instituicao', '-data_recebimento'], name='audios_disp_institu_7d085d_idx'),
        ),
        migrations.AddIndex(
            model_name='audiodispositivo',
            index=models.Index(fields=['status'], name='audios_disp_status_d49e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='audiodispositivo',
            constraint=models.UniqueConstraint(fields=('dispositivo', 'upload_id'), name='uniq_audio_por_dispositivo_upload'),
        ),
    ]
