# Generated by Django 5.2.15 on 2026-08-03 14:52
#
# Uma professora pode atender mais de uma turma: a FK única `turma` vira o M2M
# `turmas` (escopo de permissão do gravador) + `turma_ativa` (a turma corrente,
# trocada por voz durante a gravação).
#
# ORDEM IMPORTA: os campos novos são criados e os vínculos existentes copiados
# ANTES de remover a FK antiga — o autogerado do Django removia primeiro e
# perderia os dados.

import django.db.models.deletion
from django.db import migrations, models


def copiar_turma_para_turmas(apps, schema_editor):
    """Preserva o vínculo atual: turma (FK) -> turmas (M2M) + turma_ativa."""
    DispositivoGravador = apps.get_model('api', 'DispositivoGravador')
    CodigoPareamento = apps.get_model('api', 'CodigoPareamento')

    for dispositivo in DispositivoGravador.objects.exclude(turma__isnull=True):
        dispositivo.turmas.add(dispositivo.turma)
        # com uma única turma, ela já é a ativa
        dispositivo.turma_ativa_id = dispositivo.turma_id
        dispositivo.save(update_fields=['turma_ativa'])

    for codigo in CodigoPareamento.objects.exclude(turma__isnull=True):
        codigo.turmas.add(codigo.turma)


def reverter(apps, schema_editor):
    """Volta a primeira turma do M2M para a FK (perde as demais, por natureza)."""
    DispositivoGravador = apps.get_model('api', 'DispositivoGravador')
    CodigoPareamento = apps.get_model('api', 'CodigoPareamento')

    for dispositivo in DispositivoGravador.objects.all():
        primeira = dispositivo.turmas.first()
        if primeira:
            dispositivo.turma_id = primeira.id
            dispositivo.save(update_fields=['turma'])

    for codigo in CodigoPareamento.objects.all():
        primeira = codigo.turmas.first()
        if primeira:
            codigo.turma_id = primeira.id
            codigo.save(update_fields=['turma'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_modelos_dispositivo_gravador'),
    ]

    operations = [
        # 1. cria os campos novos
        migrations.AddField(
            model_name='codigopareamento',
            name='turmas',
            field=models.ManyToManyField(blank=True, db_table='codigos_pareamento_turmas', related_name='codigos_pareamento', to='api.turma', verbose_name='Turmas do vínculo'),
        ),
        migrations.AddField(
            model_name='dispositivogravador',
            name='turmas',
            field=models.ManyToManyField(blank=True, db_table='dispositivos_gravador_turmas', related_name='dispositivos_gravador', to='api.turma', verbose_name='Turmas atendidas'),
        ),
        migrations.AddField(
            model_name='dispositivogravador',
            name='turma_ativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_com_turma_ativa', to='api.turma', verbose_name='Turma ativa (definida por voz)'),
        ),
        # 2. migra os dados existentes
        migrations.RunPython(copiar_turma_para_turmas, reverter),
        # 3. só então remove a FK antiga
        migrations.RemoveField(
            model_name='codigopareamento',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='dispositivogravador',
            name='turma',
        ),
    ]
