# Generated by Django 5.2.4 on 2026-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_instituicao_logo_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='foto_storage_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chave da Foto no Storage'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='foto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto'),
        ),
    ]
